config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories, only: :show
  resources :tags, only: :show
  resources :upload, controller: :assets, as: :assets, only: :create

  resources :users, param: :name do
    resources :entries, only: :new
    resources :entries, except: [:new, :show], param: :slug, constraints: { format: false } do
      collection do
        get '*slug/edit', action: :edit
        get '*slug', action: :show
        put '*slug', action: :update
        patch '*slug', action: :update
        delete '*slug', action: :destroy
      end
    end
  end

  resource :profile, controller: :profile, only: [:show, :edit, :update] do
    collection do
      get :entries
      get :activities
    end
  end

  resources :pages, only: [:show]

  namespace :admin do
    resource :dashboard, only: [:show]

    resources :users
    resources :entries
    resources :categories, only: [:index, :create]
    resources :assets
    resources :advertisements do
      member do
        post :move_lower
        post :move_higher
        post :move_to_bottom
        post :move_to_top
      end
    end
    resources :navigations do
      member do
        post :move_lower
        post :move_higher
        post :move_to_bottom
        post :move_to_top
      end
    end
    resources :recommends do
      member do
        post :move_lower
        post :move_higher
        post :move_to_bottom
        post :move_to_top
      end
    end
    resources :pages
    resources :trackers
    resource :blog, controller: :blog, only: [:show, :edit, :update]

    get :profile, controller: :users

    root to: 'dashboard#show'
  end

  get '/feed', to: 'home#feed', as: :feed, defaults: { format: 'atom' }

  # for DoRuby
  get ':user_name/:date/*slug', to: 'entries#doruby', constraints: { date: /\d{8}/, slug: /[^\/]*/, format: false }
  get ':user_name/files/*filename', to: 'entries#doruby_file', constraints: { filename: /[^\/]*/, format: false }
  get '/blog/feed_all' => redirect('/feed')

  root to: 'home#index'
end

app/models/recommend.rb
class Recommend < ActiveRecord::Base
  acts_as_list scope: :category

  belongs_to :category
  belongs_to :entry

  validates :category, presence: true
  validates :entry, presence: true

  default_scope -> { order(:position) }

  delegate :title, to: :entry
end

app/controllers/admin/recommends_controller.rb
module Admin
  class RecommendsController < Admin::ApplicationController
    before_action :set_recommend, only: [:show, :edit, :update, :destroy, :move_lower, :move_higher, :move_to_bottom, :move_to_top]

    def index
      @recommends = Recommend.all
    end

    def show
      render :edit
    end

    def new
      @recommend = Recommend.new(category_id: params[:category_id])
    end

    def edit
    end

    def create
      @recommend = Recommend.new(recommend_params)

      if @recommend.save
        redirect_to [:admin, @recommend], notice: 'Recommend was successfully created.'
      else
        render :new
      end
    end

    def update
      if @recommend.update(recommend_params)
        redirect_to [:admin, @recommend], notice: 'Recommend was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @recommend.destroy
      redirect_to admin_recommends_url, notice: 'Recommend was successfully destroyed.'
    end

    def move_lower
      @recommend.move_lower
      redirect_to admin_recommends_url, notice: 'Recommend was successfully moved.'
    end

    def move_higher
      @recommend.move_higher
      redirect_to admin_recommends_url, notice: 'Recommend was successfully moved.'
    end

    def move_to_bottom
      @recommend.move_to_bottom
      redirect_to admin_recommends_url, notice: 'Recommend was successfully moved.'
    end

    def move_to_top
      @recommend.move_to_top
      redirect_to admin_recommends_url, notice: 'Recommend was successfully moved.'
    end

    private

    def set_recommend
      @recommend = Recommend.find(params[:id])
    end

    def recommend_params
      params.fetch(:recommend, {}).permit(
        :category_id,
        :entry_id
      )
    end
  end
end

app/views/admin/recommends/_form.slim
= form_for [:admin, @recommend] do |f|
  = error_messages_for @recommend

  fieldset
    .col-md-3
      legend
        | 一般

    .col-md-9
      .form-group
        = f.label :category_id
        = f.collection_select :category_id, Category.roots, :id, :name

      .form-group
        = f.label :entry_id
        = f.collection_select :entry_id, [@recommend.entry].compact, :id, :title, {}, class: 'select2 ajax', data: { source: admin_entries_path, term: :title_cont_all }

  .hidden
    = f.submit

app/views/admin/recommends/edit.slim
.admin-panel
  .admin-panel-fixed-top
    .admin-panel-heading
      ul.pull-right.list-inline
        li
          = link_to_save

      h1.page-header
        ol.breadcrumb
          li>
            = link_to 'おすすめ', admin_recommends_path
          li.active
            = @recommend.title

  .admin-panel-body
    = render 'form'
    hr
    .panel.panel-danger
      .panel-heading type="button" data-toggle="collapse" data-target="#danger-collapse"
        strong
          span.fa.fa-angle-down>
          | 削除する
      #danger-collapse.collapse
        .panel-body
          p
            | この操作は元に戻せません。本当に削除してもよろしいですか？
          = link_to '削除する', [:admin, @recommend], method: :delete, class: 'btn btn-danger'

app/views/admin/recommends/index.slim
.admin-panel
  .admin-panel-heading
    ul.pull-right.list-inline
      li
        = link_to '新規作成', new_admin_recommend_path, class: 'btn btn-default'

    h1.page-header
      | おすすめ
      small<
        | #{@recommends.count} 件

  .admin-panel-body
    section
      - Category.roots.each do |category|
        h3
          = category.name
          span<
            = link_to '追加', new_admin_recommend_path(category_id: category), class: 'btn btn-default'

        - recommends = @recommends.where(category_id: category)
        - if recommends.empty?
          | レコードが見つかりませんでした。
        - else
          table.table.table-striped
            thead
              th
                = recommends.klass.human_attribute_name(:entry_id)
              th
              th
                = recommends.klass.human_attribute_name(:updated_at)
              th
                = recommends.klass.human_attribute_name(:created_at)
              th
                = recommends.klass.human_attribute_name(:position)
            tbody
              - recommends.each do |recommend|
                tr
                  td
                    = link_to recommend.title, [:admin, recommend]
                  td
                    = link_to '編集', [:admin, recommend.entry]
                    span<>
                      | |
                    = link_to 'プレビュー', [recommend.entry.user, recommend.entry], target: '_blank'

                  td
                    = l recommend.updated_at
                  td
                    = l recommend.created_at
                  td
                    .btn-group
                      = link_to move_to_bottom_admin_recommend_path(recommend), class: 'btn btn-default', method: :post do
                        span.fa.fa-angle-double-down
                      = link_to move_lower_admin_recommend_path(recommend), class: 'btn btn-default', method: :post do
                        span.fa.fa-angle-down
                      = link_to move_higher_admin_recommend_path(recommend), class: 'btn btn-default', method: :post do
                        span.fa.fa-angle-up
                      = link_to move_to_top_admin_recommend_path(recommend), class: 'btn btn-default', method: :post do
                        span.fa.fa-angle-double-up

app/views/admin/recommends/new.slim
.admin-panel
  .admin-panel-fixed-top
    .admin-panel-heading
      ul.pull-right.list-inline
        li
          = link_to_save

      h1.page-header
        ol.breadcrumb
          li>
            = link_to 'おすすめ', admin_recommends_path
          li.active
            | 新規作成

  .admin-panel-body
    = render 'form'