config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories, only: :show
  resources :tags, only: :show
  resources :upload, controller: :assets, as: :assets, only: :create

  resources :users, param: :name do
    resources :entries, only: :new
    resources :entries, except: [:new, :show], param: :slug, constraints: { format: false } do
      collection do
        get '*slug/edit', action: :edit
        get '*slug', action: :show
        put '*slug', action: :update
        patch '*slug', action: :update
        delete '*slug', action: :destroy
      end
    end
  end

  resource :profile, controller: :profile, only: [:show, :edit, :update] do
    collection do
      get :entries
      get :activities
    end
  end

  resources :pages, only: [:show]

  namespace :admin do
    resource :dashboard, only: [:show]

    resources :users
    resources :entries
    resources :categories, only: [:index, :create]
    resources :assets
    resources :advertisements do
      member do
        post :move_lower
        post :move_higher
        post :move_to_bottom
        post :move_to_top
      end
    end
    resources :navigations do
      member do
        post :move_lower
        post :move_higher
        post :move_to_bottom
        post :move_to_top
      end
    end
    resources :recommends do
      member do
        post :move_lower
        post :move_higher
        post :move_to_bottom
        post :move_to_top
      end
    end
    resources :pages
    resources :trackers
    resource :blog, controller: :blog, only: [:show, :edit, :update]

    get :profile, controller: :users

    root to: 'dashboard#show'
  end

  get '/feed', to: 'home#feed', as: :feed, defaults: { format: 'atom' }

  # for DoRuby
  get ':user_name/:date/*slug', to: 'entries#doruby', constraints: { date: /\d{8}/, slug: /[^\/]*/, format: false }
  get ':user_name/files/*filename', to: 'entries#doruby_file', constraints: { filename: /[^\/]*/, format: false }
  get '/blog/feed_all' => redirect('/feed')

  root to: 'home#index'
end

app/views/shared/_entries.slim
.entries
  - entries.each do |entry|
    - user = entry.user

    .media
      .media-left
        .crop
          = link_to [user, entry] do
            span class="image" style="background-image:url('#{image_url(entry.eye_catch_image_url)}');"

      .media-body
        h4.media-heading
          = link_to entry.title, [user, entry], class: "#{'draft' if entry.draft}"
          - if entry.draft
            small<
              | 下書き
        = strip_tags entry.headline

        .media-footer
          ul.pull-right.list-inline
            - if current_user == user
              li
                = link_to edit_user_entry_path(user, entry), class: 'btn btn-default' do
                  i.fa.fa-edit>
                  | 編集
              li
                = link_to [user, entry], data: { confirm: '本当に削除してもよろしいですか？' }, method: :delete, class: 'btn btn-danger' do
                  i.fa.fa-trash>
                  | 削除
            li
              = l entry.created_at.to_date
            li
              = number_with_delimiter entry.views_count
              small<
                | views
          ul.list-inline
            li
              = link_to gravatar_tag(user, class: 'img-circle', size: 40), user
            li
              = link_to user.nickname, user

- if entries.respond_to? :current_page
  .pagination-group.text-center
    .pagination-group-next
      - next_count = [entries.total_count - (per_page * entries.current_page), per_page].min
      - if next_count.positive?
        = link_to_next_page entries, "次の#{next_count}件をみる", class: 'btn-next-page'

    = paginate entries

app/views/shared/_facebook_page_plugin.html.erb
<% url = Blog.instance.facebook_page_url %>
<div class="fb-page" data-href="<%= url %>" data-width="500" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="<%= url %>"><a href="<%= url %>">Facebook</a></blockquote></div></div>

app/views/shared/_facebook_sdk.slim
#fb-root
javascript:
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.6";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

app/views/shared/_follow_feedly.html.erb
<% url = CGI.escape(feed_url) %>
<a href='http://cloud.feedly.com/#subscription%2Ffeed%2F<%= url %>' target='blank'><img id='feedlyFollow' src='http://s3.feedly.com/img/follows/feedly-follow-rectangle-flat-big_2x.png' alt='follow us in feedly' width='131' height='56'></a>

app/views/shared/_follow_twitter.html.erb
<% user_name = Blog.instance.twitter_uid %>
<a href="https://twitter.com/<%= user_name %>" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @<%= user_name %></a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/shared/_footer.slim
footer
  .container
    .row
      - 4.times.each do |index|
        .col-md-3
          ul.list-unstyled
            = render 'shared/navigations', location: :footer, page: index + 1, per_page: 4

  hr

  .container
    p.text-muted
      | Copyright (c) 2016

app/views/shared/_header.slim
nav.navbar.navbar-default
  .container
    .navbar-header
      button.navbar-toggle.collapsed type="button" class="" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      .navbar-brand
        = link_to root_path do
          - title_words = Blog.instance.title.underscore.split('_')
          - title_first_word = title_words.first
          - title_other_word = (title_words - [title_first_word]).join('_')
          span
            = title_first_word.camelize
          - if title_other_word
            strong
              = title_other_word.camelize
    #navbar.navbar-collapse.collapse
      ul.nav.navbar-nav.navbar-right
        - case
        - when user_signed_in?
          li
            = link_to profile_path do
              = gravatar_tag current_user, class: 'img-circle', id: 'header-gravatar'
              = current_user.nickname
          li
            = link_to 'サインアウト', destroy_user_session_path, method: :delete
        - when sign_in_page?
        - else
          = render 'shared/navigations', location: :header

nav.navbar.navbar-inverse
  .container
    .navbar-collapse
      ul.nav.navbar-nav
        - case
        - when sign_in_page?
          li
            = link_to "ようこそ！ #{Blog.instance.title}へ", '#'
        - when profile_page?
          li
            = link_to 'ホーム', activities_profile_path, class: "#{'active' if controller_name == 'profile' && action_name == 'activities' }"
          li
            = link_to '記事', entries_profile_path, class: "#{'active' if controller_name == 'profile' && action_name == 'entries' }"
          li
            = link_to 'プロフィール編集', edit_profile_path, class: "#{'active' if controller_name == 'profile' && action_name == 'edit' }"
        - else
          = render 'shared/navigations', location: :nav

      - if user_signed_in?
        ul.nav.navbar-nav.navbar-right
          li
            = link_to new_user_entry_path(current_user), class: 'btn-new-entry' do
              i.fa.fa-pencil>
              | 記事を書く

app/views/shared/_navigations.slim
- page ||= nil
- per_page ||= nil

- navigations = Navigation.active.where(location: location).page(page).per(per_page)

- cache navigations.cache_key do
  - if navigations.any?
    - navigations.each do |navigation|
      li
        = link_to navigation.name, navigation.url
  - else
    - case location.to_sym
    - when :header
      li
        = link_to "#{Blog.instance.title}とは", '#'
      li
        = link_to 'お問い合わせ', '#'
    - when :nav
      - Category.roots.each do |category|
        li
          = link_to category.name, category

app/views/shared/_notifier.slim
- if notice.present?
  p#notice
    = notice

app/views/shared/_profile_card.slim
- is_author = (current_user == user)
- entries = user.entries.published

#profile-card
  .panel.panel-default
    .panel-body
      .media
        .media-left
          = link_to gravatar_tag(user, class: 'img-circle media-object'), (is_author ? edit_gravatar_path : user_path(user)), target: "#{'_blank' if is_author}"
        .media-body
          h4.media-heading
            = link_to user.nickname, (is_author ? edit_profile_path : user_path(user))

          ul.list-inline
            li
              dl
                dt
                  | 記事数
                dd.text-center
                  = entries.count
            li
              dl
                dt
                  | 最終投稿
                dd.text-center
                  - if entries.any?
                    = time_ago_in_words entries.maximum(:created_at)
                  - else
                    | -
    - if user.profile.present?
      .panel-footer
        = strip_tags user.profile

app/views/shared/_sidebar.slim
- ads = Advertisement.all
- first_ads = [ads.first].compact
- other_ads = ads - [ads.first]

- if controller_name.to_sym == :home
  = render 'shared/sidebar/advertisements', advertisements: first_ads
  = render 'shared/sidebar/popular_entries'
  = render 'shared/sidebar/newest_entries'
  = render 'shared/sidebar/facebook'
  = render 'shared/sidebar/categories'
  = render 'shared/sidebar/advertisements', advertisements: other_ads
- else
  - if controller_name.to_sym == :entries && action_name.to_sym == :index
    = render 'shared/profile_card', user: @user
  = render 'shared/sidebar/categories'
  = render 'shared/sidebar/advertisements', advertisements: first_ads
  = render 'shared/sidebar/popular_entries'
  = render 'shared/sidebar/newest_entries'
  = render 'shared/sidebar/facebook'
  = render 'shared/sidebar/advertisements', advertisements: other_ads

app/views/shared/_trackers.slim
- trackers = Tracker.active.where(location: location)
- cache trackers.cache_key do
  - trackers.each do |tracker|
    = tracker.code.html_safe