config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories, only: :show
  resources :tags, only: :show
  resources :upload, controller: :assets, as: :assets, only: :create

  resources :users, param: :name do
    resources :entries, only: :new
    resources :entries, except: [:new, :show], param: :slug, constraints: { format: false } do
      collection do
        get '*slug/edit', action: :edit
        get '*slug', action: :show
        put '*slug', action: :update
        patch '*slug', action: :update
        delete '*slug', action: :destroy
      end
    end
  end

  resource :profile, controller: :profile, only: [:show, :edit, :update] do
    collection do
      get :entries
      get :activities
    end
  end

  resources :pages, only: [:show]

  namespace :admin do
    resource :dashboard, only: [:show]

    resources :users
    resources :entries
    resources :categories, only: [:index, :create]
    resources :assets
    resources :advertisements do
      member do
        post :move_lower
        post :move_higher
        post :move_to_bottom
        post :move_to_top
      end
    end
    resources :navigations do
      member do
        post :move_lower
        post :move_higher
        post :move_to_bottom
        post :move_to_top
      end
    end
    resources :recommends do
      member do
        post :move_lower
        post :move_higher
        post :move_to_bottom
        post :move_to_top
      end
    end
    resources :pages
    resources :trackers
    resource :blog, controller: :blog, only: [:show, :edit, :update]

    get :profile, controller: :users

    root to: 'dashboard#show'
  end

  get '/feed', to: 'home#feed', as: :feed, defaults: { format: 'atom' }

  # for DoRuby
  get ':user_name/:date/*slug', to: 'entries#doruby', constraints: { date: /\d{8}/, slug: /[^\/]*/, format: false }
  get ':user_name/files/*filename', to: 'entries#doruby_file', constraints: { filename: /[^\/]*/, format: false }
  get '/blog/feed_all' => redirect('/feed')

  root to: 'home#index'
end

app/models/navigation.rb
class Navigation < ActiveRecord::Base
  extend Enumerize

  validates :name, presence: true, length: { maximum: 255 }
  validates :url, length: { maximum: 255 }
  validates :location, presence: true

  scope :active, -> { where(active: true) }
  scope :by_newest, -> { reorder(created_at: :desc) }

  default_scope -> { order(:position) }

  acts_as_list scope: [:location]

  enumerize :location, in: %i(
    header
    nav
    footer
  )

  class << self
    def cache_key
      location = all.where_values_hash['location'] if all.respond_to? :where_values_hash
      page = all.current_page if all.respond_to? :current_page
      maximum_updated_at = maximum(:updated_at)
      timestamp = maximum_updated_at.utc.to_s(cache_timestamp_format) if maximum_updated_at
      "#{model_name.cache_key}/all-#{[location, page, timestamp, count].compact.join('-')}"
    end
  end
end

app/controllers/admin/navigations_controller.rb
module Admin
  class NavigationsController < Admin::ApplicationController
    before_action :set_navigation, only: [:show, :edit, :update, :destroy, :move_lower, :move_higher, :move_to_bottom, :move_to_top]

    def index
      @navigations = Navigation.all
    end

    def show
      render :edit
    end

    def new
      @navigation = Navigation.new(location: params[:location])
    end

    def edit
    end

    def create
      @navigation = Navigation.new(navigation_params)

      if @navigation.save
        redirect_to [:admin, @navigation], notice: 'Navigation was successfully created.'
      else
        render :new
      end
    end

    def update
      if @navigation.update(navigation_params)
        redirect_to [:admin, @navigation], notice: 'Navigation was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @navigation.destroy
      redirect_to admin_navigations_url, notice: 'Navigation was successfully destroyed.'
    end

    def move_lower
      @navigation.move_lower
      redirect_to admin_navigations_url, notice: 'Navigation was successfully moved.'
    end

    def move_higher
      @navigation.move_higher
      redirect_to admin_navigations_url, notice: 'Navigation was successfully moved.'
    end

    def move_to_bottom
      @navigation.move_to_bottom
      redirect_to admin_navigations_url, notice: 'Navigation was successfully moved.'
    end

    def move_to_top
      @navigation.move_to_top
      redirect_to admin_navigations_url, notice: 'Navigation was successfully moved.'
    end

    private

    def set_navigation
      @navigation = Navigation.find(params[:id])
    end

    def navigation_params
      params.fetch(:navigation, {}).permit(
        :active,
        :name,
        :url,
        :location
      )
    end
  end
end

app/views/admin/navigations/_form.slim
= form_for [:admin, @navigation] do |f|
  = error_messages_for @navigation

  fieldset
    .col-md-3
      legend
        | 一般

    .col-md-9
      .form-group
        .checkbox
          = f.label :active do
            = f.check_box :active
            = f.object.class.human_attribute_name(:active)

      .form-group
        = f.label :name
        = f.text_field :name

      .form-group
        = f.label :url
        = f.text_field :url

      .form-group
        = f.label :location
        = f.select :location, f.object.class.location.options

  .hidden
    = f.submit

app/views/admin/navigations/edit.slim
.admin-panel
  .admin-panel-fixed-top
    .admin-panel-heading
      ul.pull-right.list-inline
        li
          = link_to_save

      h1.page-header
        ol.breadcrumb
          li>
            = link_to 'ナビゲーション', admin_navigations_path
          li.active
            = @navigation.name

  .admin-panel-body
    = render 'form'
    hr
    .panel.panel-danger
      .panel-heading type="button" data-toggle="collapse" data-target="#danger-collapse"
        strong
          span.fa.fa-angle-down>
          | 削除する
      #danger-collapse.collapse
        .panel-body
          p
            | この操作は元に戻せません。本当に削除してもよろしいですか？
          = link_to '削除する', [:admin, @navigation], method: :delete, class: 'btn btn-danger'

app/views/admin/navigations/index.slim
.admin-panel
  .admin-panel-heading
    ul.pull-right.list-inline
      li
        = link_to '新規作成', new_admin_navigation_path, class: 'btn btn-default'

    h1.page-header
      | ナビゲーション
      small<
        | #{@navigations.count} 件

  .admin-panel-body
    section
      - @navigations.klass.location.values.each do |location|
        h3
          = location.humanize
          span<
            = link_to '追加', new_admin_navigation_path(location: location), class: 'btn btn-default'

        - navigations = @navigations.where(location: location)
        - if navigations.empty?
          | レコードが見つかりませんでした。
        - else
          table.table.table-striped
            thead
              th
                = navigations.klass.human_attribute_name(:active)
              th
                = navigations.klass.human_attribute_name(:name)
              th
                = navigations.klass.human_attribute_name(:updated_at)
              th
                = navigations.klass.human_attribute_name(:created_at)
              th
                = navigations.klass.human_attribute_name(:position)
            tbody
              - navigations.each do |navigation|
                tr
                  td
                    - if navigation.active?
                      | ✔︎
                  td
                    = link_to navigation.name, [:admin, navigation]
                    br
                    small.text-muted
                      = navigation.url
                  td
                    = l navigation.updated_at
                  td
                    = l navigation.created_at
                  td
                    .btn-group
                      = link_to move_to_bottom_admin_navigation_path(navigation), class: 'btn btn-default', method: :post do
                        span.fa.fa-angle-double-down
                      = link_to move_lower_admin_navigation_path(navigation), class: 'btn btn-default', method: :post do
                        span.fa.fa-angle-down
                      = link_to move_higher_admin_navigation_path(navigation), class: 'btn btn-default', method: :post do
                        span.fa.fa-angle-up
                      = link_to move_to_top_admin_navigation_path(navigation), class: 'btn btn-default', method: :post do
                        span.fa.fa-angle-double-up

app/views/admin/navigations/new.slim
.admin-panel
  .admin-panel-fixed-top
    .admin-panel-heading
      ul.pull-right.list-inline
        li
          = link_to_save

      h1.page-header
        ol.breadcrumb
          li>
            = link_to 'ナビゲーション', admin_navigations_path
          li.active
            | 新規作成

  .admin-panel-body
    = render 'form'