config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories, only: :show
  resources :tags, only: :show
  resources :upload, controller: :assets, as: :assets, only: :create

  resources :users, param: :name do
    resources :entries, only: :new
    resources :entries, except: [:new, :show], param: :slug, constraints: { format: false } do
      collection do
        get '*slug/edit', action: :edit
        get '*slug', action: :show
        put '*slug', action: :update
        patch '*slug', action: :update
        delete '*slug', action: :destroy
      end
    end
  end

  resource :profile, controller: :profile, only: [:show, :edit, :update] do
    collection do
      get :entries
      get :activities
    end
  end

  resources :pages, only: [:show]

  namespace :admin do
    resource :dashboard, only: [:show]

    resources :users
    resources :entries
    resources :categories, only: [:index, :create]
    resources :assets
    resources :advertisements do
      member do
        post :move_lower
        post :move_higher
        post :move_to_bottom
        post :move_to_top
      end
    end
    resources :navigations do
      member do
        post :move_lower
        post :move_higher
        post :move_to_bottom
        post :move_to_top
      end
    end
    resources :recommends do
      member do
        post :move_lower
        post :move_higher
        post :move_to_bottom
        post :move_to_top
      end
    end
    resources :pages
    resources :trackers
    resource :blog, controller: :blog, only: [:show, :edit, :update]

    get :profile, controller: :users

    root to: 'dashboard#show'
  end

  get '/feed', to: 'home#feed', as: :feed, defaults: { format: 'atom' }

  # for DoRuby
  get ':user_name/:date/*slug', to: 'entries#doruby', constraints: { date: /\d{8}/, slug: /[^\/]*/, format: false }
  get ':user_name/files/*filename', to: 'entries#doruby_file', constraints: { filename: /[^\/]*/, format: false }
  get '/blog/feed_all' => redirect('/feed')

  root to: 'home#index'
end

app/models/tracker.rb
class Tracker < ActiveRecord::Base
  extend Enumerize

  validates :name, presence: true, length: { maximum: 255 }
  validates :tracker_id, length: { maximum: 255 }
  validates :code, presence: true
  validates :location, presence: true

  scope :active, -> { where(active: true) }
  scope :by_newest, -> { reorder(created_at: :desc) }

  enumerize :location, in: %i(
    after_opening_body
    before_closing_body
    head
  ), scope: true

  class << self
    def cache_key
      location = all.where_values_hash['location'] if all.respond_to? :where_values_hash
      maximum_updated_at = maximum(:updated_at)
      timestamp = maximum_updated_at.utc.to_s(cache_timestamp_format) if maximum_updated_at
      "#{model_name.cache_key}/all-#{[location, timestamp, count].compact.join('-')}"
    end
  end
end

app/controllers/admin/trackers_controller.rb
module Admin
  class TrackersController < Admin::ApplicationController
    before_action :set_tracker, only: [:show, :edit, :update, :destroy]

    def index
      @trackers = Tracker.by_newest
    end

    def show
      render :edit
    end

    def new
      @tracker = Tracker.new
    end

    def edit
    end

    def create
      @tracker = Tracker.new(tracker_params)

      if @tracker.save
        redirect_to [:admin, @tracker], notice: 'Tracker was successfully created.'
      else
        render :new
      end
    end

    def update
      if @tracker.update(tracker_params)
        redirect_to [:admin, @tracker], notice: 'Tracker was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @tracker.destroy
      redirect_to admin_trackers_url, notice: 'Tracker was successfully destroyed.'
    end

    private

    def set_tracker
      @tracker = Tracker.find(params[:id])
    end

    def tracker_params
      params.fetch(:tracker, {}).permit(
        :active,
        :name,
        :tracker_id,
        :code,
        :location
      )
    end
  end
end

app/views/admin/trackers/_form.slim
= form_for [:admin, @tracker] do |f|
  = error_messages_for @tracker

  fieldset
    .col-md-3
      legend
        | 一般

    .col-md-9
      .form-group
        .checkbox
          = f.label :active do
            = f.check_box :active
            = f.object.class.human_attribute_name(:active)

      .form-group
        = f.label :name
        = f.text_field :name

      .form-group
        = f.label :tracker_id
        = f.text_field :tracker_id

      .form-group
        = f.label :code
        = f.text_area :code, rows: 10

      .form-group
        = f.label :location
        = f.select :location, f.object.class.location.options

  .hidden
    = f.submit

app/views/admin/trackers/edit.slim
.admin-panel
  .admin-panel-fixed-top
    .admin-panel-heading
      ul.pull-right.list-inline
        li
          = link_to_save

      h1.page-header
        ol.breadcrumb
          li>
            = link_to 'トラッキング情報', admin_trackers_path
          li.active
            = @tracker.name
            small<
              = @tracker.tracker_id

  .admin-panel-body
    = render 'form'
    hr
    .panel.panel-danger
      .panel-heading type="button" data-toggle="collapse" data-target="#danger-collapse"
        strong
          span.fa.fa-angle-down>
          | 削除する
      #danger-collapse.collapse
        .panel-body
          p
            | この操作は元に戻せません。本当に削除してもよろしいですか？
          = link_to '削除する', [:admin, @tracker], method: :delete, class: 'btn btn-danger'

app/views/admin/trackers/index.slim
.admin-panel
  .admin-panel-heading
    ul.pull-right.list-inline
      li
        = link_to '新規作成', new_admin_tracker_path, class: 'btn btn-default'

    h1.page-header
      | トラッキング情報
      small<
        | #{@trackers.count} 件

  .admin-panel-body
    section
      - if @trackers.empty?
        | レコードが見つかりませんでした。
      - else
        table.table.table-striped
          thead
            th
              = @trackers.klass.human_attribute_name(:active)
            th
              = @trackers.klass.human_attribute_name(:name)
            th
              = @trackers.klass.human_attribute_name(:updated_at)
            th
              = @trackers.klass.human_attribute_name(:created_at)
          tbody
            - @trackers.each do |tracker|
              tr
                td
                  - if tracker.active?
                    | ✔︎
                td
                  = link_to tracker.name, [:admin, tracker]
                  br
                  small.text-muted
                    = tracker.tracker_id
                td
                  = l tracker.updated_at
                td
                  = l tracker.created_at

app/views/admin/trackers/new.slim
.admin-panel
  .admin-panel-fixed-top
    .admin-panel-heading
      ul.pull-right.list-inline
        li
          = link_to_save

      h1.page-header
        ol.breadcrumb
          li>
            = link_to 'トラッキング情報', admin_trackers_path
          li.active
            | 新規作成

  .admin-panel-body
    = render 'form'